version: '3.0'

services:
  grafana:
    platform: 'linux/amd64'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3000:3000/tcp
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
