name: 🐛 Bug Report
description: Report an issue with the Snowflake Grafana datasource plugin
title: "🐛: "
labels: [bug]
assignees:
  - 'devnied'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much information as possible to help us reproduce and fix the issue.

  - type: input
    id: grafana-version
    attributes:
      label: Grafana Version
      description: What version of Grafana are you using?
      placeholder: e.g., 10.2.3
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Snowflake Datasource Plugin Version
      description: What version of the Snowflake Grafana datasource plugin are you using?
      placeholder: e.g., v2.1.0
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS is Grafana running on?
      placeholder: e.g., Ubuntu 22.04, Windows 11, Docker
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Please describe the issue you're experiencing.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Describe the steps to reproduce the issue.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs or Screenshots
      description: Add any logs, error messages, or screenshots that could help us understand the issue.
      render: shell
    validations:
      required: false